ALTER TABLE holdings ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE holdings ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE holdings ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX idx_holdings_deleted_at ON holdings(deleted_at);
